//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactusi_Wpf.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cactus()
        {
            this.Cactus_Vistavka = new HashSet<Cactus_Vistavka>();
        }
    
        public int ID_Cactus { get; set; }
        public Nullable<int> ID_Vid { get; set; }
        public Nullable<int> ID_Proishozhdenie { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Age { get; set; }
        public string Instructions { get; set; }
        public string Cactus_Name { get; set; }
        public byte[] Photo { get; set; }
        public string Rewards { get; set; }
    
        public virtual Proishozhdenie Proishozhdenie { get; set; }
        public virtual Vid Vid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cactus_Vistavka> Cactus_Vistavka { get; set; }
    }
}
