//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactusi_Wpf.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Praktika_RPM1Entities3 : DbContext
    {
        public Praktika_RPM1Entities3()
            : base("name=Praktika_RPM1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cactus> Cactus { get; set; }
        public virtual DbSet<Cactus_Vistavka> Cactus_Vistavka { get; set; }
        public virtual DbSet<Proishozhdenie> Proishozhdenie { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vid> Vid { get; set; }
        public virtual DbSet<Vistavka> Vistavka { get; set; }
    }
}
